package re.bytecode.obfuscat.dsl;

/** This class is not actually used :< */
public class SupportedOpcodes {
    public static final int NOP = 0; 
//    public static final int ACONST_NULL = 1; //CONSTANT
    public static final int ICONST_M1 = 2; //CONSTANT
    public static final int ICONST_0 = 3; //CONSTANT
    public static final int ICONST_1 = 4; //CONSTANT
    public static final int ICONST_2 = 5; //CONSTANT
    public static final int ICONST_3 = 6; //CONSTANT
    public static final int ICONST_4 = 7; //CONSTANT
    public static final int ICONST_5 = 8; //CONSTANT
//    public static final int LCONST_0 = 9; //CONSTANT
//    public static final int LCONST_1 = 10; //CONSTANT
//    public static final int FCONST_0 = 11; //CONSTANT
//    public static final int FCONST_1 = 12; //CONSTANT
//    public static final int FCONST_2 = 13; //CONSTANT
//    public static final int DCONST_0 = 14; //CONSTANT
//    public static final int DCONST_1 = 15; //CONSTANT
    public static final int BIPUSH = 16; //CONSTANT
    public static final int SIPUSH = 17; //CONSTANT
    public static final int LDC = 18; //CONSTANT
    public static final int LDC_W = 19; //CONSTANT
//    public static final int LDC2_W = 20; //CONSTANT
    public static final int ILOAD = 21; //LOCALVAR
//    public static final int LLOAD = 22;  //LOCALVAR
//    public static final int FLOAD = 23; //LOCALVAR
//    public static final int DLOAD = 24; //LOCALVAR
    public static final int ALOAD = 25; //LOCALVAR
    public static final int ILOAD_0 = 26; //LOCALVAR
    public static final int ILOAD_1 = 27; //LOCALVAR
    public static final int ILOAD_2 = 28; //LOCALVAR
    public static final int ILOAD_3 = 29; //LOCALVAR
//    public static final int LLOAD_0 = 30; //LOCALVAR
//    public static final int LLOAD_1 = 31; //LOCALVAR
//    public static final int LLOAD_2 = 32; //LOCALVAR
//    public static final int LLOAD_3 = 33; //LOCALVAR
//    public static final int FLOAD_0 = 34; //LOCALVAR
//    public static final int FLOAD_1 = 35; //LOCALVAR
//    public static final int FLOAD_2 = 36; //LOCALVAR
//    public static final int FLOAD_3 = 37; //LOCALVAR
//    public static final int DLOAD_0 = 38; //LOCALVAR
//    public static final int DLOAD_1 = 39; //LOCALVAR
//    public static final int DLOAD_2 = 40; //LOCALVAR
//    public static final int DLOAD_3 = 41; //LOCALVAR
    public static final int ALOAD_0 = 42; //LOCALVAR
    public static final int ALOAD_1 = 43; //LOCALVAR
    public static final int ALOAD_2 = 44; //LOCALVAR
    public static final int ALOAD_3 = 45; //LOCALVAR
    public static final int IALOAD = 46; //AVAR
//    public static final int LALOAD = 47; //AVAR
//    public static final int FALOAD = 48; //AVAR
//    public static final int DALOAD = 49; //AVAR
//    public static final int AALOAD = 50; //AVAR
    public static final int BALOAD = 51; //AVAR
    public static final int CALOAD = 52; //AVAR
    public static final int SALOAD = 53; //AVAR
    public static final int ISTORE = 54; //LOCALVAR
//    public static final int LSTORE = 55; //LOCALVAR
//    public static final int FSTORE = 56; //LOCALVAR
//    public static final int DSTORE = 57; //LOCALVAR
//    public static final int ASTORE = 58; //LOCALVAR
    public static final int ISTORE_0 = 59; //LOCALVAR
    public static final int ISTORE_1 = 60; //LOCALVAR
    public static final int ISTORE_2 = 61; //LOCALVAR
    public static final int ISTORE_3 = 62; //LOCALVAR
//    public static final int LSTORE_0 = 63; //LOCALVAR
//    public static final int LSTORE_1 = 64; //LOCALVAR
//    public static final int LSTORE_2 = 65; //LOCALVAR
//    public static final int LSTORE_3 = 66; //LOCALVAR
//    public static final int FSTORE_0 = 67; //LOCALVAR
//    public static final int FSTORE_1 = 68; //LOCALVAR
//    public static final int FSTORE_2 = 69; //LOCALVAR
//    public static final int FSTORE_3 = 70; //LOCALVAR
//    public static final int DSTORE_0 = 71; //LOCALVAR
//    public static final int DSTORE_1 = 72; //LOCALVAR
//    public static final int DSTORE_2 = 73; //LOCALVAR
//    public static final int DSTORE_3 = 74; //LOCALVAR
//    public static final int ASTORE_0 = 75; //LOCALVAR
//    public static final int ASTORE_1 = 76; //LOCALVAR
//    public static final int ASTORE_2 = 77; //LOCALVAR
//    public static final int ASTORE_3 = 78; //LOCALVAR
    public static final int IASTORE = 79; //AVAR
//    public static final int LASTORE = 80; //AVAR
//    public static final int FASTORE = 81; //AVAR
//    public static final int DASTORE = 82; //AVAR
//    public static final int AASTORE = 83; //AVAR
    public static final int BASTORE = 84; //AVAR
    public static final int CASTORE = 85; //AVAR
    public static final int SASTORE = 86; //AVAR
    public static final int POP = 87; //STACK
//    public static final int POP2 = 88; //STACK
    public static final int DUP = 89; //STACK
    public static final int DUP_X1 = 90; //STACK
    public static final int DUP_X2 = 91; //STACK
//    public static final int DUP2 = 92; //STACK
//    public static final int DUP2_X1 = 93; //STACK
//    public static final int DUP2_X2 = 94; //STACK
    public static final int SWAP = 95; //STACK
    public static final int IADD = 96;  //MATH
//    public static final int LADD = 97; //MATH
//    public static final int FADD = 98; //MATH
//    public static final int DADD = 99; //MATH
    public static final int ISUB = 100; //MATH
//    public static final int LSUB = 101; //MATH
//    public static final int FSUB = 102; //MATH
//    public static final int DSUB = 103; //MATH
    public static final int IMUL = 104; //MATH
//    public static final int LMUL = 105; //MATH
//    public static final int FMUL = 106; //MATH
//    public static final int DMUL = 107; //MATH
    public static final int IDIV = 108; //MATH
//    public static final int LDIV = 109; //MATH
//    public static final int FDIV = 110; //MATH
//    public static final int DDIV = 111; //MATH
    public static final int IREM = 112; //MATH
//    public static final int LREM = 113; //MATH
//    public static final int FREM = 114; //MATH
//    public static final int DREM = 115; //MATH
    public static final int INEG = 116; //MATH
//    public static final int LNEG = 117; //MATH
//    public static final int FNEG = 118; //MATH
//    public static final int DNEG = 119; //MATH
    public static final int ISHL = 120; //MATH
//    public static final int LSHL = 121; //MATH
    public static final int ISHR = 122; //MATH
//    public static final int LSHR = 123; //MATH
    public static final int IUSHR = 124; //MATH
//    public static final int LUSHR = 125; //MATH
    public static final int IAND = 126; //MATH
//    public static final int LAND = 127; //MATH
    public static final int IOR = 128; //MATH
//    public static final int LOR = 129; //MATH
    public static final int IXOR = 130; //MATH
//    public static final int LXOR = 131; //MATH
    public static final int IINC = 132; //MATH
//    public static final int I2L = 133; //CONVERT
//    public static final int I2F = 134; //CONVERT
//    public static final int I2D = 135; //CONVERT
//    public static final int L2I = 136; //CONVERT
//    public static final int L2F = 137; //CONVERT
//    public static final int L2D = 138; //CONVERT
//    public static final int F2I = 139; //CONVERT
//    public static final int F2L = 140; //CONVERT
//    public static final int F2D = 141; //CONVERT
//    public static final int D2I = 142; //CONVERT
//    public static final int D2L = 143; //CONVERT
//    public static final int D2F = 144; //CONVERT
    public static final int I2B = 145; //CONVERT
    public static final int I2C = 146; //CONVERT
    public static final int I2S = 147; //CONVERT
//    public static final int LCMP = 148; //COMPARE
//    public static final int FCMPL = 149; //COMPARE
//    public static final int FCMPG = 150; //COMPARE
//    public static final int DCMPL = 151; //COMPARE
//    public static final int DCMPG = 152; //COMPARE
    public static final int IFEQ = 153; //BRANCH
    public static final int IFNE = 154; //BRANCH
    public static final int IFLT = 155; //BRANCH
    public static final int IFGE = 156; //BRANCH
    public static final int IFGT = 157; //BRANCH
    public static final int IFLE = 158; //BRANCH
    public static final int IF_ICMPEQ = 159; //BRANCH
    public static final int IF_ICMPNE = 160; //BRANCH
    public static final int IF_ICMPLT = 161; //BRANCH
    public static final int IF_ICMPGE = 162; //BRANCH
    public static final int IF_ICMPGT = 163; //BRANCH
    public static final int IF_ICMPLE = 164; //BRANCH
//    public static final int IF_ACMPEQ = 165; //BRANCH
//    public static final int IF_ACMPNE = 166; //BRANCH
    public static final int GOTO = 167; //BRANCH
//    public static final int JSR = 168; //BRANCH                  // QUESTIONABLE WHETHER EVEN USED BY JAVA
//    public static final int RET = 169; //BRANCH                  // QUESTIONABLE WHETHER EVEN USED BY JAVA
    public static final int TABLESWITCH = 170; //TABLE           // MAYBE LATER
    public static final int LOOKUPSWITCH = 171; //TABLE          // MAYBE LATER
//    public static final int IRETURN = 172; //BRANCH              // NOT REALLY NEEDED
//    public static final int LRETURN = 173; //BRANCH
//    public static final int FRETURN = 174; //BRANCH
//    public static final int DRETURN = 175; //BRANCH
//    public static final int ARETURN = 176; //BRANCH              // NOT REALLY NEEDED
    public static final int RETURN = 177; //BRANCH
    public static final int GETSTATIC = 178; //VAR
    public static final int PUTSTATIC = 179; //VAR
//    public static final int GETFIELD = 180; //VAR
//    public static final int PUTFIELD = 181; //VAR
//    public static final int INVOKEVIRTUAL = 182; //BRANCH
//    public static final int INVOKESPECIAL = 183; //BRANCH
//    public static final int INVOKESTATIC = 184; //BRANCH          // MAYBE LATER FOR API CALLS N SUCH
//    public static final int INVOKEINTERFACE = 185; //BRANCH
//    public static final int INVOKEDYNAMIC = 186; //BRANCH
//    public static final int NEW = 187; 
//    public static final int NEWARRAY = 188; 						// NEEDED IN <CLINIT>
//    public static final int ANEWARRAY = 189; 
//    public static final int ARRAYLENGTH = 190;
//    public static final int ATHROW = 191; //STACK
//    public static final int CHECKCAST = 192; 
//    public static final int INSTANCEOF = 193; //COMPARE
//    public static final int MONITORENTER = 194; 
//    public static final int MONITOREXIT = 195; 
//    public static final int WIDE = 196;
//    public static final int MULTIANEWARRAY = 197; 
//    public static final int IFNULL = 198; //BRANCH
//    public static final int IFNONNULL = 199; //BRANCH
//    public static final int GOTO_W = 200; //BRANCH
//    public static final int JSR_W = 201; //BRANCH
    
}